
USE CheckItDB;

DROP TABLE IF EXISTS User;
CREATE TABLE IF NOT EXISTS User(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nickname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Category;
CREATE TABLE IF NOT EXISTS Category(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Tag;
CREATE TABLE IF NOT EXISTS Tag(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS List;
CREATE TABLE IF NOT EXISTS List(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL, 
    category_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES Category(id),
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Item;
CREATE TABLE IF NOT EXISTS Item(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    status BOOLEAN NOT NULL,
    list_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(list_id) REFERENCES List(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Item_Tag;
CREATE TABLE IF NOT EXISTS Item_Tag(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    item_id INT UNSIGNED NOT NULL,
    tag_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(item_id) REFERENCES Item(id) ON DELETE CASCADE,
	FOREIGN KEY(tag_id) REFERENCES Tag(id)
);

SHOW TABLES;

SELECT * FROM User;

ALTER TABLE Category ADD COLUMN icon VARCHAR(100) NOT NULL;

INSERT INTO Category (name, icon) VALUES
('Voyage', 'bi-suitcase-lg-fill'),
('Travail', 'bi-person-workspace');

SELECT * FROM Category;
SELECT * FROM List;
SELECT * FROM Item;

INSERT INTO Category (name, icon) VALUES
('Courses', 'bi-cart-fill'),
('Cadeaux', 'bi-gift-fill');

INSERT INTO Tag(name) VALUES ('Urgent'), ('Important'), ('En cours'), ('À vérifier'), ('À acheter');

SELECT * FROM Tag;

SELECT * FROM Item_Tag;

SELECT Item_Tag* , Tag.name as tag_name 
FROM Item_Tag as IT 
INNER JOIN Tag ON IT.tag_id = Tag.id









